ALTER TABLE "Model" DROP CONSTRAINT IF EXISTS "Model_fk0";

ALTER TABLE "Model" DROP CONSTRAINT IF EXISTS "Model_fk1";

ALTER TABLE "Car" DROP CONSTRAINT IF EXISTS "Car_fk0";

ALTER TABLE "Car" DROP CONSTRAINT IF EXISTS "Car_fk1";

ALTER TABLE "Car" DROP CONSTRAINT IF EXISTS "Car_fk2";

ALTER TABLE "Car" DROP CONSTRAINT IF EXISTS "Car_fk3";

